feat(docs): add cheatseet for ML07
OWASP/www-project-machine-learning-security-top-10 pull request #207
Opened 2024-03-15 19:24 UTC by aryanxk02

This PR adds cheatsheet for transfer learning attack. 
Ref: https://github.com/OWASP/www-project-machine-learning-security-top-10/issues/155
CC: @shsingh @techiemac

2024-03-16 16:09 UTC, techiemac requested changes
Thanks for the PR! I think overall this should come from the lens of transfer learning attack mitigations and not necessarily what transfer learning is.

2024-03-16 16:10 UTC, techiemac requested changes

2024-03-16 16:10 UTC, techiemac commented on Top10MLSummary.md
> +## ML01:2023 Input Manipulation Attack
For now, let's hold off on the summaries. I appreciate the ownership but work still needs to be done on the core docs. I think once that is complete, we will just lift the Description of each one into the respective summaries.

2024-03-27 06:00 UTC, aryanxk02 commented on docs/cheatsheets/ML02_2023-Transfer-Learning-Attack-Cheatsheet.md
> +#### Implementation
Thanks for the review @techiemac. What mitigations here for transfer learning attack. And how much should be the content?

2024-03-27 06:02 UTC, aryanxk02 commented on docs/cheatsheets/ML02_2023-Transfer-Learning-Attack-Cheatsheet.md
> +#### Introduction
Alright, got it!

2024-03-27 06:03 UTC, aryanxk02 commented on docs/cheatsheets/ML02_2023-Transfer-Learning-Attack-Cheatsheet.md
> +#### Strategies
I'll research and add around 4-5 risks associated with transfer learning attack.

2024-03-27 06:04 UTC, aryanxk02 commented on docs/cheatsheets/ML02_2023-Transfer-Learning-Attack-Cheatsheet.md
> +#### Implementation
And do I enhance the Strategies part or completely replace it with the mitigations?

2024-03-27 06:04 UTC, aryanxk02 commented on docs/cheatsheets/ML02_2023-Transfer-Learning-Attack-Cheatsheet.md
> +```python
Okay, I will have to go through the repo once and check what's the content in there :)

2024-03-27 06:04 UTC, aryanxk02 commented on docs/cheatsheets/ML02_2023-Transfer-Learning-Attack-Cheatsheet.md
> +### Best Practices
Thanks, got it!

2024-03-27 06:05 UTC, aryanxk02 commented on docs/cheatsheets/ML02_2023-Transfer-Learning-Attack-Cheatsheet.md
> +### Conclusion
Okay, I'll make the changes.

2025-04-15 21:38 UTC, closed without merging