new version of ML06
OWASP/www-project-machine-learning-security-top-10 pull request #211
Opened 2024-06-24 20:16 UTC by mik0w

New version of ML06 - I've included MLOps software as a part of AI Supply Chain and added examples

2024-07-16 21:12 UTC, shsingh requested changes
Hi @mik0w as per https://github.com/OWASP/www-project-machine-learning-security-top-10/issues/188#issuecomment-1829141861

do you want to revert the ris to be called ML Supply Chain Attacks instead of AI Supply Chain Attacks to keep it consistent throughout the document?

We can be more specific on mentioning ML and AI in terms of differentiation somewhere in the project summary.

2024-07-17 10:57 UTC, mik0w commented
@shsingh - sure thing, I will change the name to ML Supply Chain

2024-08-27 09:14 UTC, mik0w commented
@shsingh Can it be merged now? :)

2024-09-06 04:12 UTC, sagarbhure approved these changes

2024-09-06 04:13 UTC, merged